require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Ban. As you add validations to Ban, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Ban.create! valid_attributes
      get bans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ban = Ban.create! valid_attributes
      get ban_url(ban)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ban_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      ban = Ban.create! valid_attributes
      get edit_ban_url(ban)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ban" do
        expect {
          post bans_url, params: { ban: valid_attributes }
        }.to change(Ban, :count).by(1)
      end

      it "redirects to the created ban" do
        post bans_url, params: { ban: valid_attributes }
        expect(response).to redirect_to(ban_url(Ban.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ban" do
        expect {
          post bans_url, params: { ban: invalid_attributes }
        }.to change(Ban, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bans_url, params: { ban: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ban" do
        ban = Ban.create! valid_attributes
        patch ban_url(ban), params: { ban: new_attributes }
        ban.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ban" do
        ban = Ban.create! valid_attributes
        patch ban_url(ban), params: { ban: new_attributes }
        ban.reload
        expect(response).to redirect_to(ban_url(ban))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ban = Ban.create! valid_attributes
        patch ban_url(ban), params: { ban: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ban" do
      ban = Ban.create! valid_attributes
      expect {
        delete ban_url(ban)
      }.to change(Ban, :count).by(-1)
    end

    it "redirects to the bans list" do
      ban = Ban.create! valid_attributes
      delete ban_url(ban)
      expect(response).to redirect_to(bans_url)
    end
  end
end
